modLoader = "javafml"
loaderVersion = "[40,)"
license = "GPLv3"
[[mods]]
modId = "tinkersdisassemble"
version = "1.0.0"
displayName = "Tinkers Disassembler"
authors = "rinko1231"
description = '''
Disassemble TiC tools
'''
